### ISSUE TITLE
Ubuntu-22.04 keeps "Waiting for SSH service"

### ISSUE THREAD

**Issue by bugoff** [test-kitchen/kitchen-digitalocean#112]
## :ghost: Brief Description

I want to start a test on ubuntu 22.04, all my other ubuntu versions are working, except 22.04.

## Version

Kitchen (v3.5.0)
Kitchen digitalocean (v0.14.2)

## Environment

Mac os  12.6
- chef-workstation 

Ubuntu 18.04
- chef-workstation                    22.7.1006-1

## Scenario

I try to run kitchen test with ubuntu 22.04 as base image.

## Steps to Reproduce

this is my .kitchen.yml file

```
---
provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: once
  channel: stable
  product_version: 18
  chef_license: accept
  client_rb:
    chef_license: accept

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - apt
      - xplose-test
    attributes:

driver:
  name: digitalocean
  region: ams3
  server_name: xplose-test
  digitalocean_access_token: xxx
  ssh_key_ids: xxx
  size: s-1vcpu-1gb
transport:
  ssh_key: "~/.ssh/id_rsa"
platforms:
- name: ubuntu-18-04
  driver:
    image: ubuntu-18-04-x64
- name: ubuntu-20-04
  driver:
    image: ubuntu-20-04-x64
- name: ubuntu-22-04
  driver:
    image: ubuntu-22-04-x64

```
run kitchen converge default-ubuntu-22-04

## Expected Result

it should run the tests.

## Actual Result

```
-----> Creating <default-ubuntu-22-04>...
       DigitalOcean instance <336261514> created.
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
..
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
       Waiting for SSH service on 206.189.11.83:22, retrying in 3 seconds
$$$$$$ [SSH] connection failed, terminating (#<Net::SSH::AuthenticationFailed: Authentication failed for user root@206.189.11.83>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [SSH session could not be established] on default-ubuntu-22-04
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```
