### ISSUE TITLE
#config[:digitalocean_client_id] cannot be blank

### ISSUE THREAD

**Issue by jmreicha** [test-kitchen/kitchen-digitalocean#26]
Not sure if I'm just inputting something incorrectly but I receive the following error when I attempt to run a `kitchen list`.

```
aboutme_admin@jenkins:/tmp/me-test-cookbook$ kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Kitchen::Driver::Digitalocean<default-ubuntu-12-10-x64>#config[:digitalocean_client_id] cannot be blank
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Here is my .kitchen.yml:

```
driver:
  name: digitalocean
  require_chef_omnibus: 11.14.2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-13-10-x64
```

I am using version 0.7.3 - Looks like I missed the newest release, how do I install?
