### ISSUE TITLE
Failed to complete #create action: unknown type of %string error

### ISSUE THREAD

**Issue by jakshi** [test-kitchen/kitchen-digitalocean#27]
When I try to create digital ocean droplet using this plugin, I got this:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [/usr/lib/ruby/gems/1.9.1/gems/kartograph-0.0.8/lib/kartograph/map.rb:33: unknown type of %string
      return unless %i(singular plural).include?(type)
                       ^
/usr/lib/ruby/gems/1.9.1/gems/kartograph-0.0.8/lib/kartograph/map.rb:33: syntax error, unexpected $end
      return unless %i(singular plural).include?(type)
                       ^]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

there's a test-kitchen config:

```

---
driver:
  name: digitalocean
  region: ams2
  size: 512mb

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12-04-x64

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    run_list:
      - recipe[jakshi-backup::default]
      - recipe[jakshi-backup-test-helper::default]
    attributes:
```

$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
