### ISSUE TITLE
configuration from README

### ISSUE THREAD

**Issue by sarkis** [test-kitchen/kitchen-digitalocean#29]
Should the following work in .kitchen.yml?

```
driver:
  - name: digitalocean

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12-04-x64
  driver_config:
    region: sfo1
    size: 512mb

suites:
- name: default
  run_list:
  - recipe[recipe::default]
  attributes: {}
```

For some reason I need to use:

```
driver:
  name: digitalocean
```

without the -, or it doesn't work.
