### ISSUE TITLE
Wish list features

### ISSUE THREAD

**Issue by gregf** [test-kitchen/kitchen-digitalocean#65]
People using this gem every day, are there any features you want that are not implemented? Changes that should be made? What can I do to improve the gem. Let me know.

**Comment by bdausses** [comment]
Is it possible to add the ability to create and attach additional volumes?  Something akin to what I'd do with Vagrant/VBOX:
```
---
driver:
  name: vagrant
  customize:
    createhd:
      -  filename: /path_to/disk1.vmdk
         size: 8192
    storageattach:
      -  storagectl: SATA Controller
         port: 1
         device: 0
         type: hdd
         medium: /path_to/disk1.vmdk
```
