### ISSUE TITLE
Remove unsupported images and add support of Ubuntu 20.04

### ISSUE THREAD

**Issue by vsingh-msys** [test-kitchen/kitchen-digitalocean#76]
# Version:
kitchen-digitalocean (0.10.6)

# Scenario:
- define .ketchen.yml

```
---
driver:
  name: digitalocean
  tags:
    - test-kitchen
    - vsingh@chef.io
    - Vivek Singh
platforms:
  - name: coreos-stable
  - name: coreos-beta
  - name: coreos-alpha
  - name: debian-7
  - name: fedora-27
  - name: fedora-28
  - name: fedora-29
  - name: freebsd-11.2
  - name: freebsd-11.1
  - name: freebsd-11.0
  - name: freebsd-10.4
  - name: freebsd-10.3
  - name: ubuntu-14
  - name: ubuntu-17
  - name: ubuntu-19

provisioner:
  name: chef_zero
  chef_license: accept
suites:
  - name: default
    run_list:
      - recipe[learn_chef_apache2::default]
```

```
> kitchen list
Instance               Driver        Provisioner  Verifier  Transport  Last Action    Last Error
default-coreos-stable  Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-coreos-beta    Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-coreos-alpha   Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-debian-7       Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-fedora-27      Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-fedora-28      Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-fedora-29      Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-freebsd-112    Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-freebsd-111    Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-freebsd-110    Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-freebsd-104    Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-freebsd-103    Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-ubuntu-14      Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-ubuntu-17      Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
default-ubuntu-19      Digitalocean  ChefZero     Busser    Ssh        <Not Created>  DropletKit::FailedCreate
```

# Steps to reproduce:

- Add any of the above-supported name images.
- `kitchen create`

# Expected Result:

it should create all the droplets supported by kitchen-digitalocean.

# Actual Result:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 15 actions failed.
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-coreos-stable
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-coreos-beta
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-coreos-alpha
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-debian-7
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-fedora-27
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-fedora-28
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-fedora-29
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-freebsd-112
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-freebsd-111
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-freebsd-110
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-freebsd-104
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-freebsd-103
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-ubuntu-14
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-ubuntu-17
>>>>>>     Failed to complete #create action: [You specified an invalid image for Droplet creation.] on default-ubuntu-19
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

# Possible fix:

Match the parity with current supported digital ocean images distribution.

```
curl -X GET -H "Authorization: Bearer $TOKEN" https://api.digitalocean.com/v2/images?type=distribution | jq '.images[].slug'
"centos-6-x32"
"centos-6-x64"
"fedora-30-x64"
"centos-7-x64"
"ubuntu-18-04-x64"
"ubuntu-16-04-x32"
"ubuntu-16-04-x64"
"ubuntu-20-04-x64"
"ubuntu-19-10-x64"
"fedora-31-x64"
"centos-8-x64"
"rancheros"
"freebsd-12-x64"
"freebsd-12-x64-zfs"
"freebsd-11-x64-ufs"
"freebsd-11-x64-zfs"
"coreos-alpha"
"coreos-beta"
"coreos-stable"
"debian-10-x64"
"debian-9-x64"
"fedora-32-x64"
```
